name: room_finder_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  nb_utils: ^4.6.16
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.1.2
  intl: ^0.17.0


  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/roomFinding/
